"""Fail-closed preparation of an extracted reproducibility bundle.

Only archive paths classified as generated by the archive-specific inventory
are removed. Immutable source, environment, manifest, and explicitly declared
external-input records are hash-checked before and after preparation.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
from pathlib import Path, PurePosixPath
import tempfile
from typing import Iterable, Mapping


BUNDLE_ROOT_NAME = "blaschke_deformation_certifier_reproducibility"
INVENTORY_NAME = "source-only-replay-inventory.json"
RECEIPT_NAME = "source-only-replay-preparation.json"
INTERNAL_MANIFEST_NAME = "reproducibility_manifest.json"
POLICY_RELATIVE = PurePosixPath(
    "Numerics/blaschke_source_only_replay_policy.json"
)
GENERATED_CLASSES = frozenset({"generated_evidence", "generated_notebook"})
IMMUTABLE_CLASSES = frozenset({
    "immutable_source_or_metadata", "immutable_external_input"
})


class SourceOnlyReplayError(RuntimeError):
    """Raised before any deletion when the bundle or inventory is unsafe."""


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for block in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def _safe_relative(value: object, *, label: str) -> PurePosixPath:
    if not isinstance(value, str) or not value:
        raise SourceOnlyReplayError(f"{label} must be a non-empty string.")
    path = PurePosixPath(value)
    if path.is_absolute() or value in {".", ".."} or any(
        part in {"", ".", ".."} for part in path.parts
    ):
        raise SourceOnlyReplayError(f"Unsafe {label}: {value!r}.")
    return path


def _load_object(path: Path, *, label: str) -> dict[str, object]:
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise SourceOnlyReplayError(f"Cannot read {label} at {path}: {exc}") from exc
    if not isinstance(value, dict):
        raise SourceOnlyReplayError(f"{label} must be a JSON object.")
    return value


def _validated_root(root: Path) -> Path:
    root = Path(root)
    if root.is_symlink():
        raise SourceOnlyReplayError("The bundle root must not be a symlink.")
    try:
        resolved = root.resolve(strict=True)
    except OSError as exc:
        raise SourceOnlyReplayError(f"The bundle root does not exist: {root}.") from exc
    if not resolved.is_dir() or resolved.name != BUNDLE_ROOT_NAME:
        raise SourceOnlyReplayError(
            f"Expected the exact extracted bundle directory named {BUNDLE_ROOT_NAME!r}."
        )
    if resolved == Path(resolved.anchor) or (resolved / ".git").exists():
        raise SourceOnlyReplayError("Refusing a broad root or Git working tree.")
    required = (
        resolved / ".final_deployment_generated",
        resolved / "REPLAY.md",
        resolved / INTERNAL_MANIFEST_NAME,
        resolved / INVENTORY_NAME,
        resolved.joinpath(*POLICY_RELATIVE.parts),
        resolved / "Numerics/blaschke_deformation_certifier_template.ipynb",
    )
    missing = [str(path) for path in required if not path.is_file()]
    if missing:
        raise SourceOnlyReplayError(
            "The directory is not an exact extracted bundle; missing: "
            + ", ".join(missing)
        )
    return resolved


def _path_under_prefix(path: PurePosixPath, prefix: PurePosixPath) -> bool:
    return path == prefix or prefix in path.parents


def classify_path(relative: PurePosixPath, policy: Mapping[str, object]) -> str:
    generated_files = {
        _safe_relative(value, label="generated file")
        for value in policy.get("generated_files", [])
    }
    generated_prefixes = tuple(
        _safe_relative(value, label="generated prefix")
        for value in policy.get("generated_prefixes", [])
    )
    external_inputs = {
        _safe_relative(value, label="immutable external input")
        for value in policy.get("immutable_external_inputs", [])
    }
    if relative in generated_files:
        return "generated_notebook"
    if any(_path_under_prefix(relative, prefix) for prefix in generated_prefixes):
        return "generated_evidence"
    if relative in external_inputs:
        return "immutable_external_input"
    return "immutable_source_or_metadata"


def make_archive_inventory(
    *,
    staging_root: Path,
    file_records: Iterable[Mapping[str, object]],
) -> dict[str, object]:
    """Classify staged archive records and bind each one to its staged hash."""

    policy_path = staging_root.joinpath(*POLICY_RELATIVE.parts)
    policy = _load_object(policy_path, label="source-only replay policy")
    if policy.get("schema_version") != 1 or policy.get("bundle_root_name") != BUNDLE_ROOT_NAME:
        raise SourceOnlyReplayError("The source-only replay policy schema is invalid.")
    files: list[dict[str, object]] = []
    seen: set[PurePosixPath] = set()
    for record in file_records:
        relative = _safe_relative(record.get("archive_path"), label="archive path")
        if relative in seen:
            raise SourceOnlyReplayError(f"Duplicate archive path: {relative}.")
        seen.add(relative)
        path = staging_root.joinpath(*relative.parts)
        if not path.is_file() or path.is_symlink():
            raise SourceOnlyReplayError(f"Inventory path is not a regular file: {relative}.")
        observed = sha256_file(path)
        if observed != record.get("sha256"):
            raise SourceOnlyReplayError(f"Staged hash drift for {relative}.")
        files.append({
            "path": relative.as_posix(),
            "classification": classify_path(relative, policy),
            "bytes": path.stat().st_size,
            "sha256": observed,
        })
    files.sort(key=lambda row: str(row["path"]))
    counts = {
        classification: sum(row["classification"] == classification for row in files)
        for classification in sorted(GENERATED_CLASSES | IMMUTABLE_CLASSES)
    }
    return {
        "schema_version": 1,
        "bundle_root_name": BUNDLE_ROOT_NAME,
        "policy_path": POLICY_RELATIVE.as_posix(),
        "policy_sha256": sha256_file(policy_path),
        "complete_file_set_excludes": [INVENTORY_NAME, INTERNAL_MANIFEST_NAME],
        "counts": counts,
        "files": files,
        "external_input_classification": (
            "No external numerical inputs are required when immutable_external_input is zero; "
            "all files below Numerics/outputs are generated intra-workflow evidence."
        ),
    }


def _inventory_records(
    root: Path,
) -> tuple[dict[str, object], dict[PurePosixPath, dict[str, object]]]:
    inventory_path = root / INVENTORY_NAME
    inventory = _load_object(inventory_path, label="source-only replay inventory")
    if inventory.get("schema_version") != 1 or inventory.get("bundle_root_name") != BUNDLE_ROOT_NAME:
        raise SourceOnlyReplayError("The source-only replay inventory schema is invalid.")
    policy_path = root.joinpath(*POLICY_RELATIVE.parts)
    if inventory.get("policy_path") != POLICY_RELATIVE.as_posix() or inventory.get("policy_sha256") != sha256_file(policy_path):
        raise SourceOnlyReplayError("The source-only replay policy hash has drifted.")
    rows = inventory.get("files")
    if not isinstance(rows, list) or not rows:
        raise SourceOnlyReplayError("The source-only replay inventory is empty.")
    records: dict[PurePosixPath, dict[str, object]] = {}
    for row in rows:
        if not isinstance(row, dict):
            raise SourceOnlyReplayError("Malformed source-only replay record.")
        relative = _safe_relative(row.get("path"), label="inventory path")
        classification = row.get("classification")
        if classification not in GENERATED_CLASSES | IMMUTABLE_CLASSES:
            raise SourceOnlyReplayError(f"Unknown classification for {relative}.")
        digest = row.get("sha256")
        size = row.get("bytes")
        if not isinstance(digest, str) or len(digest) != 64 or type(size) is not int:
            raise SourceOnlyReplayError(f"Malformed hash or size for {relative}.")
        if relative in records:
            raise SourceOnlyReplayError(f"Duplicate inventory path: {relative}.")
        records[relative] = row
    return inventory, records


def _actual_regular_files(root: Path) -> set[PurePosixPath]:
    files: set[PurePosixPath] = set()
    for directory, directory_names, file_names in os.walk(root, followlinks=False):
        current = Path(directory)
        for name in (*directory_names, *file_names):
            path = current / name
            if path.is_symlink():
                raise SourceOnlyReplayError(f"Symlinks are forbidden in the bundle: {path}.")
        for name in file_names:
            files.add(PurePosixPath((current / name).relative_to(root).as_posix()))
    return files


def _verify_internal_manifest(root: Path) -> None:
    manifest = _load_object(root / INTERNAL_MANIFEST_NAME, label="internal manifest")
    if manifest.get("bundle_format") != "blaschke-deformation-certifier-reproducibility-v3":
        raise SourceOnlyReplayError("Unexpected reproducibility bundle format.")
    records = manifest.get("files")
    if not isinstance(records, list):
        raise SourceOnlyReplayError("The internal manifest has no file records.")
    expected_hash = sha256_file(root / INVENTORY_NAME)
    matches = [
        row for row in records
        if isinstance(row, dict) and row.get("archive_path") == INVENTORY_NAME
    ]
    if len(matches) != 1 or matches[0].get("sha256") != expected_hash:
        raise SourceOnlyReplayError("The replay inventory is not hash-bound by the internal manifest.")


def _verify_preparation_state(root: Path, *, prepared: bool) -> tuple[dict[str, object], dict[PurePosixPath, dict[str, object]]]:
    inventory, records = _inventory_records(root)
    _verify_internal_manifest(root)
    actual = _actual_regular_files(root)
    expected = set(records) | {PurePosixPath(INVENTORY_NAME), PurePosixPath(INTERNAL_MANIFEST_NAME)}
    if prepared:
        expected -= {
            relative for relative, row in records.items()
            if row["classification"] in GENERATED_CLASSES
        }
        expected.add(PurePosixPath(RECEIPT_NAME))
    if actual != expected:
        missing = sorted(str(path) for path in expected - actual)
        unexpected = sorted(str(path) for path in actual - expected)
        raise SourceOnlyReplayError(
            f"Bundle file-set drift; missing={missing}, unexpected={unexpected}."
        )
    for relative, row in records.items():
        generated = row["classification"] in GENERATED_CLASSES
        path = root.joinpath(*relative.parts)
        if prepared and generated:
            if path.exists():
                raise SourceOnlyReplayError(f"Generated path survived preparation: {relative}.")
            continue
        if not path.is_file() or path.stat().st_size != row["bytes"] or sha256_file(path) != row["sha256"]:
            raise SourceOnlyReplayError(f"Inventory hash or size drift for {relative}.")
    return inventory, records


def _atomic_json(path: Path, value: object) -> None:
    descriptor, temporary_name = tempfile.mkstemp(
        prefix=f".{path.name}.", suffix=".tmp", dir=path.parent
    )
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8", newline="") as stream:
            json.dump(value, stream, indent=2)
            stream.write("\n")
            stream.flush()
            os.fsync(stream.fileno())
        os.replace(temporary_name, path)
    except Exception:
        try:
            os.unlink(temporary_name)
        except FileNotFoundError:
            pass
        raise


def prepare_bundle(root: Path) -> dict[str, object]:
    root = _validated_root(root)
    _, records = _verify_preparation_state(root, prepared=False)
    generated = sorted(
        (
            (relative, row) for relative, row in records.items()
            if row["classification"] in GENERATED_CLASSES
        ),
        key=lambda item: item[0].as_posix(),
    )
    if not generated:
        raise SourceOnlyReplayError("The inventory declares no generated artifacts.")
    for relative, _ in generated:
        path = root.joinpath(*relative.parts)
        path.unlink()
    candidate_directories = {
        parent
        for relative, _ in generated
        for parent in relative.parents
        if parent != PurePosixPath(".")
    }
    for relative in sorted(candidate_directories, key=lambda value: len(value.parts), reverse=True):
        directory = root.joinpath(*relative.parts)
        try:
            directory.rmdir()
        except OSError:
            pass
    receipt = {
        "schema_version": 1,
        "status": "source-only replay root prepared",
        "bundle_root_name": BUNDLE_ROOT_NAME,
        "inventory_sha256": sha256_file(root / INVENTORY_NAME),
        "removed_file_count": len(generated),
        "removed_paths": [relative.as_posix() for relative, _ in generated],
        "immutable_external_input_count": sum(
            row["classification"] == "immutable_external_input"
            for row in records.values()
        ),
    }
    _atomic_json(root / RECEIPT_NAME, receipt)
    _verify_preparation_state(root, prepared=True)
    return receipt


def check_prepared_bundle(root: Path) -> dict[str, object]:
    root = _validated_root(root)
    receipt = _load_object(root / RECEIPT_NAME, label="preparation receipt")
    _verify_preparation_state(root, prepared=True)
    return receipt


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--bundle-root", type=Path, default=Path.cwd())
    parser.add_argument("--check-prepared", action="store_true")
    args = parser.parse_args()
    receipt = (
        check_prepared_bundle(args.bundle_root)
        if args.check_prepared
        else prepare_bundle(args.bundle_root)
    )
    print(json.dumps(receipt, indent=2))


if __name__ == "__main__":
    main()
